In [6]:
from __future__ import print_function
import torch

In [3]:
torch.cuda.get_device_name(0)

'GeForce GTX 1060 6GB'

In [4]:
torch.cuda.is_available()

True

In [5]:
print(torch.__version__)

1.4.0


In [10]:
# Construct 5X3 matrix,
x = torch.empty(5, 3)
print(x)

tensor([[8.4490e-39, 9.6429e-39, 9.2755e-39],
        [1.0286e-38, 9.0919e-39, 8.9082e-39],
        [9.2755e-39, 8.4490e-39, 1.0194e-38],
        [9.0919e-39, 8.4490e-39, 8.7245e-39],
        [1.0102e-38, 1.0653e-38, 8.7245e-39]])


In [11]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6866, 0.9632, 0.2960],
        [0.8669, 0.0083, 0.1019],
        [0.9354, 0.9786, 0.0362],
        [0.2149, 0.6362, 0.0123],
        [0.0730, 0.8495, 0.4160]])


In [12]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [14]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [15]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [16]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.3128,  0.8868,  0.1326],
        [-1.2306,  0.6740, -0.3411],
        [ 0.7468,  0.3381, -2.3988],
        [-0.0822, -0.4213,  0.8072],
        [-0.4222, -0.4305, -1.0680]])


In [17]:
print(x.size())

torch.Size([5, 3])


In [18]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.3871,  1.4774,  0.8104],
        [-0.3971,  1.3694, -0.1867],
        [ 1.6738,  0.9578, -2.1881],
        [ 0.6730, -0.3664,  1.0647],
        [-0.3722, -0.0484, -0.9322]])


In [19]:
print(torch.add(x, y))

tensor([[ 0.3871,  1.4774,  0.8104],
        [-0.3971,  1.3694, -0.1867],
        [ 1.6738,  0.9578, -2.1881],
        [ 0.6730, -0.3664,  1.0647],
        [-0.3722, -0.0484, -0.9322]])


In [21]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.3871,  1.4774,  0.8104],
        [-0.3971,  1.3694, -0.1867],
        [ 1.6738,  0.9578, -2.1881],
        [ 0.6730, -0.3664,  1.0647],
        [-0.3722, -0.0484, -0.9322]])


In [22]:
y.add_(x)
print(y)

tensor([[ 0.3871,  1.4774,  0.8104],
        [-0.3971,  1.3694, -0.1867],
        [ 1.6738,  0.9578, -2.1881],
        [ 0.6730, -0.3664,  1.0647],
        [-0.3722, -0.0484, -0.9322]])


In [28]:
a = torch.tensor([4, 5])
b = torch.tensor([1, 3])
print(torch.add(a, b))
print(a.add_(b))
print(a)

tensor([5, 8])
tensor([5, 8])
tensor([5, 8])


In [29]:
print(x[:,1])

tensor([ 0.8868,  0.6740,  0.3381, -0.4213, -0.4305])
