In [11]:
from __future__ import print_function
import torch
import numpy as np

In [2]:
torch.cuda.get_device_name(0)

'GeForce GTX 1060 6GB'

In [3]:
torch.cuda.is_available()

True

In [4]:
print(torch.__version__)

1.4.0


In [10]:
# Construct 5X3 matrix,
x = torch.empty(5, 3)
print(x)

tensor([[8.4490e-39, 9.6429e-39, 9.2755e-39],
        [1.0286e-38, 9.0919e-39, 8.9082e-39],
        [9.2755e-39, 8.4490e-39, 1.0194e-38],
        [9.0919e-39, 8.4490e-39, 8.7245e-39],
        [1.0102e-38, 1.0653e-38, 8.7245e-39]])


In [11]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6866, 0.9632, 0.2960],
        [0.8669, 0.0083, 0.1019],
        [0.9354, 0.9786, 0.0362],
        [0.2149, 0.6362, 0.0123],
        [0.0730, 0.8495, 0.4160]])


In [12]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [14]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [15]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [16]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.3128,  0.8868,  0.1326],
        [-1.2306,  0.6740, -0.3411],
        [ 0.7468,  0.3381, -2.3988],
        [-0.0822, -0.4213,  0.8072],
        [-0.4222, -0.4305, -1.0680]])


In [17]:
print(x.size())

torch.Size([5, 3])


In [18]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.3871,  1.4774,  0.8104],
        [-0.3971,  1.3694, -0.1867],
        [ 1.6738,  0.9578, -2.1881],
        [ 0.6730, -0.3664,  1.0647],
        [-0.3722, -0.0484, -0.9322]])


In [19]:
print(torch.add(x, y))

tensor([[ 0.3871,  1.4774,  0.8104],
        [-0.3971,  1.3694, -0.1867],
        [ 1.6738,  0.9578, -2.1881],
        [ 0.6730, -0.3664,  1.0647],
        [-0.3722, -0.0484, -0.9322]])


In [21]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.3871,  1.4774,  0.8104],
        [-0.3971,  1.3694, -0.1867],
        [ 1.6738,  0.9578, -2.1881],
        [ 0.6730, -0.3664,  1.0647],
        [-0.3722, -0.0484, -0.9322]])


In [22]:
y.add_(x)
print(y)

tensor([[ 0.3871,  1.4774,  0.8104],
        [-0.3971,  1.3694, -0.1867],
        [ 1.6738,  0.9578, -2.1881],
        [ 0.6730, -0.3664,  1.0647],
        [-0.3722, -0.0484, -0.9322]])


In [28]:
a = torch.tensor([4, 5])
b = torch.tensor([1, 3])
print(torch.add(a, b))
print(a.add_(b))
print(a)

tensor([5, 8])
tensor([5, 8])
tensor([5, 8])


In [29]:
print(x[:,1])

tensor([ 0.8868,  0.6740,  0.3381, -0.4213, -0.4305])


- **torch.view** 크기 변경 : tensor의 size나 shape 변경

In [5]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [7]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.4110])
-0.41101494431495667


## Numpy 변환 (Bridge)
- Torch Tensor --> Numpy array 변환
- Numpy array --> Torch Tensor 변환

In [32]:
# torch tensor --> numpy
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [33]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [35]:
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [26]:
# numpy --> torch tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)

In [28]:
np.add(a, 1, out=a)
print(a)
print(b)

[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


## CUDA Tensors
- .to 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있다.

In [37]:
# "torch.device"를 사용하여 tensor를 GPU 안팎으로 이동한다.
if torch.cuda.is_available():
    device = torch.device("cuda")   # cuda 장치 객체로
    y = torch.ones_like(x, device=device)   # GPU 상에 직접 tensor를 생성하거나
    x = x.to(device)    # ''.to("cuda")''를 사용하면 됨
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([0.5890], device='cuda:0')
tensor([0.5890], dtype=torch.float64)
