In [1]:
import torch

## list --> tensor로 만들기 위해

In [2]:
a = [[123, 234, 432],[24,12,54],[24,543,67],[2,5,3],[5434,24,52]]
b = [2,1,4,4,4]

In [3]:
a_tensor = torch.tensor(a)
b_tensor = torch.tensor(b)

In [8]:
print(a_tensor, '\n', a_tensor.shape, '\n')
print(b_tensor, '\n', b_tensor.shape)

tensor([[ 123,  234,  432],
        [  24,   12,   54],
        [  24,  543,   67],
        [   2,    5,    3],
        [5434,   24,   52]]) 
 torch.Size([5, 3]) 

tensor([2, 1, 4, 4, 4]) 
 torch.Size([5])


In [9]:
dataset = torch.utils.data.TensorDataset(a_tensor, b_tensor)

In [10]:
dataLoader = torch.utils.data.DataLoader(dataset, shuffle=True, batch_size=4)

## list --> tensor로 만들기 위해
- list를 정의
- list에 행?의 개수가 일정해야 함.
- 이를 위해 최대 행길이를 정의하고 0으로 패딩
- 패딩완료 후 torch.tensor로 tensor로 만든다.

In [28]:
a = [[32, 543, 34, 54], [4, 34, 33], [25, 32, 122, 4, 342, 12],
     [12, 43], [2, 23, 43, 23, 10, 403, 23, 111]]
max_len = 20

In [29]:
padding_list = [i + [0]*(max_len-len(i)) for i in a]

In [30]:
padding_list[:3]

[[32, 543, 34, 54, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [4, 34, 33, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [25, 32, 122, 4, 342, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [31]:
padding_list_tensor = torch.tensor(padding_list)

In [32]:
padding_list_tensor

tensor([[ 32, 543,  34,  54,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0],
        [  4,  34,  33,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0],
        [ 25,  32, 122,   4, 342,  12,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0],
        [ 12,  43,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0],
        [  2,  23,  43,  23,  10, 403,  23, 111,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0]])

In [34]:
padding_list_tensor.size()

torch.Size([5, 20])

In [35]:
import numpy as np

padding_list_ = np.array([i + [0] * (max_len - len(i)) for i in a])

In [36]:
padding_list_[:2]

array([[ 32, 543,  34,  54,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [  4,  34,  33,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0]])

In [37]:
padding_list_tensor_ = torch.tensor(padding_list_)

In [38]:
padding_list_tensor_

tensor([[ 32, 543,  34,  54,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0],
        [  4,  34,  33,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0],
        [ 25,  32, 122,   4, 342,  12,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0],
        [ 12,  43,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0],
        [  2,  23,  43,  23,  10, 403,  23, 111,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0]], dtype=torch.int32)

In [39]:
padding_list_tensor_.size()

torch.Size([5, 20])

## tensor --> TensorDataset --> DataLoader
- 보통 x, y를 tensor에 넣어놓고 tensordataset으로 만들어 준다.
- tensordataset에서 Model에 넣어주기 위해 dataloader로 생성해 준다.

In [43]:
# 일단 y를 만들어준다.
y = [1, 2, 1, 4, 2]
label_tensor = torch.tensor(y)
print(label_tensor)
print(label_tensor.size())

tensor([1, 2, 1, 4, 2])
torch.Size([5])


In [44]:
# TensorDataset
dataset = torch.utils.data.TensorDataset(padding_list_tensor, label_tensor)

In [48]:
# DataLoader
dataloader = torch.utils.data.DataLoader(dataset, shuffle=True, batch_size=1)