# AUTOGRAD
- 자동 미분??

In [1]:
import torch

- .requires_grad 속성을 True 로 설정하면, 그 tensor에서 이뤄진 모든 연산들을 추적(track)하기 시작

In [14]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [15]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [16]:
print(y.grad_fn)

In [17]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


- out에 대한 역전파 진행
- out -> z -> y -> x

In [18]:
out.backward()

![image.png](https://github.com/tenjumh/PyTorch/blob/master/image/pytorch_backward.PNG?raw=True)




In [19]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [20]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


## 벡터-야코비안 곱 예제

In [21]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
    
print(y)

tensor([-1208.8010,   225.5814,  -494.3846], grad_fn=<MulBackward0>)


In [22]:
print(x)

tensor([-1.1805,  0.2203, -0.4828], requires_grad=True)


In [10]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
print(v)
y.backward(v)

print(x.grad)

tensor([1.0000e-01, 1.0000e+00, 1.0000e-04])
tensor([3.3896, 1.7848, 1.3455])


## 기초 추가

In [9]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)
y = x+2
print(y)
z=y*y*2
print(z)
z=z.mean()
print(z)

z.backward()    # dz/dx
print(x.grad)

tensor([ 0.4672, -1.4114, -0.9910], requires_grad=True)
tensor([2.4672, 0.5886, 1.0090], grad_fn=<AddBackward0>)
tensor([12.1742,  0.6928,  2.0363], grad_fn=<MulBackward0>)
tensor(4.9678, grad_fn=<MeanBackward0>)
tensor([3.2896, 0.7848, 1.3454])
