In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
x = torch.tensor([-1.0, 1.0, 2.0, 3.0])

#### softmax

In [3]:
output = torch.softmax(x, dim=0)
print(output)

tensor([0.0120, 0.0889, 0.2418, 0.6572])


In [4]:
sm = nn.Softmax(dim=0)
output = sm(x)
print(output)

tensor([0.0120, 0.0889, 0.2418, 0.6572])


#### sigmoid

In [5]:
output = torch.sigmoid(x)
print(output)

tensor([0.2689, 0.7311, 0.8808, 0.9526])


In [6]:
s = nn.Sigmoid()
output = s(x)
print(output)

tensor([0.2689, 0.7311, 0.8808, 0.9526])


#### tanh

In [7]:
output = torch.tanh(x)
print(output)

tensor([-0.7616,  0.7616,  0.9640,  0.9951])


In [8]:
t = nn.Tanh()
output = t(x)
print(output)

tensor([-0.7616,  0.7616,  0.9640,  0.9951])


#### relu

In [9]:
output = torch.relu(x)
print(output)

tensor([0., 1., 2., 3.])


In [10]:
r = nn.ReLU()
output = r(x)
print(output)

tensor([0., 1., 2., 3.])


#### Leaky relu

In [11]:
output = F.leaky_relu(x)
print(output)

tensor([-0.0100,  1.0000,  2.0000,  3.0000])


In [12]:
lrelu = nn.LeakyReLU()
output = lrelu(x)
print(output)

tensor([-0.0100,  1.0000,  2.0000,  3.0000])


In [ ]:
# case 1
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNet, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

# case 2
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNet, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.linear2 = nn.Linear(hidden_size, 1)
        
    def forward(self, x):
        out = torch.relu(self.linear1(x))
        out = torch.sigmoid(self.linear2(out))
        return out